// Regenerate the bundled reflection schema from the user's authoritative export.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { unzipSync } from 'fflate'
import protobuf from 'protobufjs'

import { generatePublishedCatalog } from './published-catalog.mjs'
import { generateReferenceCatalog } from './reference-catalog.mjs'

const archive = readFileSync(new URL('./RR_ProtobufDefinitions.zip', import.meta.url))
const root = new protobuf.Root()
protobuf.parse(
	'syntax="proto2"; package google.protobuf; message MessageOptions { extensions 1000 to max; }',
	root
)
for (const [name, bytes] of Object.entries(unzipSync(archive)).sort(([a], [b]) =>
	a.localeCompare(b)
)) {
	if (name.endsWith('.proto'))
		protobuf.parse(new TextDecoder().decode(bytes), root, { keepCase: true })
}
// The export imports the standard Timestamp but does not include the Google source.
if (!root.lookup('google.protobuf.Timestamp')) {
	protobuf.parse(
		'syntax="proto3"; package google.protobuf; message Timestamp { int64 seconds=1; int32 nanos=2; }',
		root
	)
}
root.resolveAll()
const schemaSha256 = createHash('sha256').update(archive).digest('hex')
const output = new URL('../src/cv2-agent/schema.json', import.meta.url)
writeFileSync(output, JSON.stringify(root.toJSON()) + '\n')
// Workers prohibit runtime eval. Compile protobufjs codecs here, while retaining
// reflection metadata for compiler validation and the agent's definition tools.
const reachable = new Set()
function collect(type) {
	if (reachable.has(type)) return
	reachable.add(type)
	for (const field of type.fieldsArray)
		if (field.resolvedType instanceof protobuf.Type) collect(field.resolvedType)
}
collect(root.lookupType('rec_room.PersistedRoomData'))
const code = [
	'/* eslint-disable */',
	'// Generated by cv2-schema/generate.mjs. Do not edit. No runtime eval.',
	"import protobuf from 'protobufjs/light.js'",
	"import schema from './schema.json'",
	'export const root = protobuf.Root.fromJSON(schema).resolveAll()',
	'const { Reader, Writer, util } = protobuf',
]
for (const type of [...reachable].sort((a, b) => a.fullName.localeCompare(b.fullName))) {
	type.setup()
	code.push(
		'{',
		`const type = root.lookupType(${JSON.stringify(type.fullName)})`,
		'const types = type.fieldsArray.map(field => field.resolvedType)',
		`type.ctor = ${protobuf.Type.generateConstructor(type).toString(type.name)}`,
		'const C = type.ctor'
	)
	for (const method of ['encode', 'decode', 'verify', 'fromObject', 'toObject'])
		code.push(`type.${method} = ${type[method].toString()}`)
	code.push('type.setup = function() { return this }', '}')
}
writeFileSync(
	new URL('../src/cv2-agent/generated-codecs.js', import.meta.url),
	code.join('\n') + '\n'
)
writeFileSync(
	new URL('./source.json', import.meta.url),
	JSON.stringify(
		{
			archive: 'RR_ProtobufDefinitions.zip',
			sha256: schemaSha256,
			generator: 'protobufjs 8.8.0; keepCase=true',
		},
		null,
		'\t'
	) + '\n'
)
console.info(`Generated ${fileURLToPath(output)}`)
writeFileSync(
	new URL('../src/cv2-agent/reference-catalog.json', import.meta.url),
	JSON.stringify(generateReferenceCatalog(root, schemaSha256)) + '\n'
)
writeFileSync(
	new URL('../src/cv2-agent/published-catalog.json', import.meta.url),
	JSON.stringify(generatePublishedCatalog()) + '\n'
)
